### ISSUE TITLE
Incorrect, shifted data after midnight

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [jdejaegh/irm-kmi-ha#38]
I have observed incorrect data being displayed and a shift in the days, in the hour after midnight. I will try to take corresponding screenshots later, hopefully tonight. I am just giving you a head start, in case you want.

Could this be caused by daylight saving time?

**Comment by jdejaegh** [comment]
Thanks for the heads!

To be sure: 
* is the bug about hourly forecast only?
* does it happen only when the current time is specifically after just after midnight?  Or can you already see it in the current forecast?

If you manage to take a screenshot, please enable the debug logging for the integration to get the raw JSON data as well.

Daylight saving time is not my main suspect on this.  The logic to handle the data is probably where the bug is: their API does not put a timestamp on the hourly forecast, just the hour it is related to (i.e. `'hour'='18'`).  The midnight case looks like the perfect edge case for a bug like this. 

I'll also try to capture this with a script tonight

**Comment by jdejaegh** [comment]
I managed to reproduce the error: when the current time is between midnight and 1 AM, all the hourly forecasts are shifted by +1 day.

**Comment by jdejaegh** [comment]
This is fixed and released with version [0.2.15](https://github.com/jdejaegh/irm-kmi-ha/releases/tag/0.2.15).  Other changes that require Home Assistant 2024.6 were released in the same version so it will only work with Home Assistant 2024.6 or newer

**Comment by patriiiiiiiiiick** [comment]
Updated yesterday and I still see the issue.

![Screenshot_20240608-001925](https://github.com/jdejaegh/irm-kmi-ha/assets/5151122/e7e52ee8-58a8-4590-ad8a-67fa7665b491)
![Screenshot_20240608-001950](https://github.com/jdejaegh/irm-kmi-ha/assets/5151122/244c4a70-4301-48b0-a671-e849d17f2737)

**Comment by jdejaegh** [comment]
Strange.  I'll try to reproduce it.
Did you check with the regular basic Lovelace if the behavior is buggy as well?

**Comment by jdejaegh** [comment]
The bug in daily forecast is fixed in [0.2.16](https://github.com/jdejaegh/irm-kmi-ha/releases/tag/0.2.16)

Thanks for your feedback on this issue.  Feel free to comment here if you still encounter that bug (hopefully not)
